### ISSUE TITLE
Error when building on OSX

### ISSUE THREAD

**Issue by npinochet** [Murii/CLove#22]
Hi, I tried compiling this project but I got this error:
```
[ 98%] Built target openal-info
[ 99%] Generating moc_mainwindow.cxx
[ 99%] Generating ui_mainwindow.h
Scanning dependencies of target alsoft-config
[ 99%] Building CXX object src/3rdparty/openal/utils/alsoft-config/CMakeFiles/alsoft-config.dir/main.cpp.o
error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'
make[2]: *** [src/3rdparty/openal/utils/alsoft-config/CMakeFiles/alsoft-config.dir/main.cpp.o] Error 1
make[1]: *** [src/3rdparty/openal/utils/alsoft-config/CMakeFiles/alsoft-config.dir/all] Error 2
make: *** [all] Error 2
```
I dont' know much about cmake, make or c so i'm not sure what's the problem, it could be i'm missing a dependancy maybe or something? I dont' know.
Thanks!

**Comment by Murii** [comment]
Hi,I know exactly what the problem is but since my macbook's keyboard decided to not work any more I wont be able to fix anything related to CLove plus the framework is not quite ready to be used at this moment because I got to finish the 3D api and still have the normal 2D api.
As soon as I get a new keyboard I'll fix everything in 2 days max.
Thanks for patience !

**Comment by npinochet** [comment]
Thanks for the quick reply! It's ok I'll wait then. I hope I'll learn some c from this project. Thanks a lot.

**Comment by Murii** [comment]
@npinochet I managed to compile the project just fine by installing brew and then call under osx 10.11.11:
brew install gcc cmake 

Let me know if this helps

**Comment by npinochet** [comment]
Thanks! that was exactly it, I was using clang insted of gcc. Keep up this great project.
